<?php
/**
 * Created by PhpStorm.
 * User: Francis
 * Date: 2.04.2023
 * Time: 2:43
 */
namespace App\Repositories\traits;

trait CurrencyTrait
{
    public static function currencyStore(): array
    {
        return [
            'AFA' => ['name' => 'Afghan Afghani', 'symbol' => '؋', 'id' => 1],
            'ALL' => ['name' => 'Albanian Lek', 'symbol' => 'Lek', 'id' => 2],
            'DZD' => ['name' => 'Algerian Dinar', 'symbol' => 'دج', 'id' => 3],
            'AOA' => ['name' => 'Angolan Kwanza', 'symbol' => 'Kz', 'id' => 4],
            'ARS' => ['name' => 'Argentine Peso', 'symbol' => '$', 'id' => 5],
            'AMD' => ['name' => 'Armenian Dram', 'symbol' => '֏', 'id' => 6],
            'AWG' => ['name' => 'Aruban Florin', 'symbol' => 'ƒ', 'id' => 7],
            'AUD' => [
                'name' => 'Australian Dollar',
                'symbol' => '$',
                'id' => 8,
            ],
            'AZN' => [
                'name' => 'Azerbaijani Manat',
                'symbol' => 'm',
                'id' => 9,
            ],
            'BSD' => [
                'name' => 'Bahamian Dollar',
                'symbol' => 'B$',
                'id' => 10,
            ],
            'BHD' => [
                'name' => 'Bahraini Dinar',
                'symbol' => '.د.ب',
                'id' => 11,
            ],
            'BDT' => [
                'name' => 'Bangladeshi Taka',
                'symbol' => '৳',
                'id' => 12,
            ],
            'BBD' => [
                'name' => 'Barbadian Dollar',
                'symbol' => 'Bds$',
                'id' => 13,
            ],
            'BYN' => [
                'name' => 'Belarusian Ruble',
                'symbol' => 'Br',
                'id' => 14,
            ],
            'BEF' => ['name' => 'Belgian Franc', 'symbol' => 'fr', 'id' => 15],
            'BZD' => ['name' => 'Belize Dollar', 'symbol' => '$', 'id' => 16],
            'BMD' => ['name' => 'Bermudan Dollar', 'symbol' => '$', 'id' => 17],
            'BTN' => [
                'name' => 'Bhutanese Ngultrum',
                'symbol' => 'Nu.',
                'id' => 18,
            ],
            'BTC' => ['name' => 'Bitcoin', 'symbol' => '฿', 'id' => 19],
            'BOB' => [
                'name' => 'Bolivian Boliviano',
                'symbol' => 'Bs.',
                'id' => 20,
            ],
            'BAM' => [
                'name' => 'Bosnia-Herzegovina Convertible Mark',
                'symbol' => 'KM',
                'id' => 21,
            ],
            'BWP' => ['name' => 'Botswanan Pula', 'symbol' => 'P', 'id' => 22],
            'BRL' => ['name' => 'Brazilian Real', 'symbol' => 'R$', 'id' => 23],
            'GBP' => [
                'name' => 'British Pound Sterling',
                'symbol' => '£',
                'id' => 24,
            ],
            'BND' => ['name' => 'Brunei Dollar', 'symbol' => 'B$', 'id' => 25],
            'BGN' => ['name' => 'Bulgarian Lev', 'symbol' => 'Лв.', 'id' => 26],
            'BIF' => [
                'name' => 'Burundian Franc',
                'symbol' => 'FBu',
                'id' => 27,
            ],
            'KHR' => [
                'name' => 'Cambodian Riel',
                'symbol' => 'KHR',
                'id' => 28,
            ],
            'CAD' => ['name' => 'Canadian Dollar', 'symbol' => '$', 'id' => 29],
            'CVE' => [
                'name' => 'Cape Verdean Escudo',
                'symbol' => '$',
                'id' => 30,
            ],
            'KYD' => [
                'name' => 'Cayman Islands Dollar',
                'symbol' => '$',
                'id' => 31,
            ],
            'XOF' => [
                'name' => 'CFA Franc BCEAO',
                'symbol' => 'CFA',
                'id' => 32,
            ],
            'XAF' => [
                'name' => 'CFA Franc BEAC',
                'symbol' => 'FCFA',
                'id' => 33,
            ],
            'XPF' => ['name' => 'CFP Franc', 'symbol' => '₣', 'id' => 34],
            'CLP' => ['name' => 'Chilean Peso', 'symbol' => '$', 'id' => 35],
            'CLF' => [
                'name' => 'Chilean Unit of Account',
                'symbol' => 'CLF',
                'id' => 36,
            ],
            'CNY' => ['name' => 'Chinese Yuan', 'symbol' => '¥', 'id' => 37],
            'COP' => ['name' => 'Colombian Peso', 'symbol' => '$', 'id' => 38],
            'KMF' => ['name' => 'Comorian Franc', 'symbol' => 'CF', 'id' => 39],
            'CDF' => [
                'name' => 'Congolese Franc',
                'symbol' => 'FC',
                'id' => 40,
            ],
            'CRC' => [
                'name' => 'Costa Rican Colón',
                'symbol' => '₡',
                'id' => 41,
            ],
            'HRK' => ['name' => 'Croatian Kuna', 'symbol' => 'kn', 'id' => 42],
            'CUC' => [
                'name' => 'Cuban Convertible Peso',
                'symbol' => '$, CUC',
                'id' => 43,
            ],
            'CZK' => [
                'name' => 'Czech Republic Koruna',
                'symbol' => 'Kč',
                'id' => 44,
            ],
            'DKK' => ['name' => 'Danish Krone', 'symbol' => 'Kr.', 'id' => 45],
            'DJF' => [
                'name' => 'Djiboutian Franc',
                'symbol' => 'Fdj',
                'id' => 46,
            ],
            'DOP' => ['name' => 'Dominican Peso', 'symbol' => '$', 'id' => 47],
            'XCD' => [
                'name' => 'East Caribbean Dollar',
                'symbol' => '$',
                'id' => 48,
            ],
            'EGP' => [
                'name' => 'Egyptian Pound',
                'symbol' => 'ج.م',
                'id' => 49,
            ],
            'ERN' => [
                'name' => 'Eritrean Nakfa',
                'symbol' => 'Nfk',
                'id' => 50,
            ],
            'EEK' => ['name' => 'Estonian Kroon', 'symbol' => 'kr', 'id' => 51],
            'ETB' => [
                'name' => 'Ethiopian Birr',
                'symbol' => 'Nkf',
                'id' => 52,
            ],
            'EUR' => ['name' => 'Euro', 'symbol' => '€', 'id' => 53],
            'FKP' => [
                'name' => 'Falkland Islands Pound',
                'symbol' => '£',
                'id' => 54,
            ],
            'FJD' => ['name' => 'Fijian Dollar', 'symbol' => 'FJ$', 'id' => 55],
            'GMD' => ['name' => 'Gambian Dalasi', 'symbol' => 'D', 'id' => 56],
            'GEL' => ['name' => 'Georgian Lari', 'symbol' => 'ლ', 'id' => 57],
            'DEM' => ['name' => 'German Mark', 'symbol' => 'DM', 'id' => 58],
            'GHS' => ['name' => 'Ghanaian Cedi', 'symbol' => 'GH₵', 'id' => 59],
            'GIP' => ['name' => 'Gibraltar Pound', 'symbol' => '£', 'id' => 60],
            'GRD' => [
                'name' => 'Greek Drachma',
                'symbol' => '₯, Δρχ, Δρ',
                'id' => 61,
            ],
            'GTQ' => [
                'name' => 'Guatemalan Quetzal',
                'symbol' => 'Q',
                'id' => 62,
            ],
            'GNF' => ['name' => 'Guinean Franc', 'symbol' => 'FG', 'id' => 63],
            'GYD' => [
                'name' => 'Guyanaese Dollar',
                'symbol' => '$',
                'id' => 64,
            ],
            'HTG' => ['name' => 'Haitian Gourde', 'symbol' => 'G', 'id' => 65],
            'HNL' => [
                'name' => 'Honduran Lempira',
                'symbol' => 'L',
                'id' => 66,
            ],
            'HKD' => [
                'name' => 'Hong Kong Dollar',
                'symbol' => '$',
                'id' => 67,
            ],
            'HUF' => [
                'name' => 'Hungarian Forint',
                'symbol' => 'Ft',
                'id' => 68,
            ],
            'ISK' => [
                'name' => 'Icelandic Króna',
                'symbol' => 'kr',
                'id' => 69,
            ],
            'INR' => ['name' => 'Indian Rupee', 'symbol' => '₹', 'id' => 70],
            'IDR' => [
                'name' => 'Indonesian Rupiah',
                'symbol' => 'Rp',
                'id' => 71,
            ],
            'IRR' => ['name' => 'Iranian Rial', 'symbol' => '﷼', 'id' => 72],
            'IQD' => ['name' => 'Iraqi Dinar', 'symbol' => 'د.ع', 'id' => 73],
            'ILS' => [
                'name' => 'Israeli New Sheqel',
                'symbol' => '₪',
                'id' => 74,
            ],
            'ITL' => ['name' => 'Italian Lira', 'symbol' => 'L,£', 'id' => 75],
            'JMD' => [
                'name' => 'Jamaican Dollar',
                'symbol' => 'J$',
                'id' => 76,
            ],
            'JPY' => ['name' => 'Japanese Yen', 'symbol' => '¥', 'id' => 77],
            'JOD' => [
                'name' => 'Jordanian Dinar',
                'symbol' => 'ا.د',
                'id' => 78,
            ],
            'KZT' => [
                'name' => 'Kazakhstani Tenge',
                'symbol' => 'лв',
                'id' => 79,
            ],
            'KES' => [
                'name' => 'Kenyan Shilling',
                'symbol' => 'KSh',
                'id' => 80,
            ],
            'KWD' => ['name' => 'Kuwaiti Dinar', 'symbol' => 'ك.د', 'id' => 81],
            'KGS' => ['name' => 'Kyrgystani Som', 'symbol' => 'лв', 'id' => 82],
            'LAK' => ['name' => 'Laotian Kip', 'symbol' => '₭', 'id' => 83],
            'LVL' => ['name' => 'Latvian Lats', 'symbol' => 'Ls', 'id' => 84],
            'LBP' => ['name' => 'Lebanese Pound', 'symbol' => '£', 'id' => 85],
            'LSL' => ['name' => 'Lesotho Loti', 'symbol' => 'L', 'id' => 86],
            'LRD' => ['name' => 'Liberian Dollar', 'symbol' => '$', 'id' => 87],
            'LYD' => ['name' => 'Libyan Dinar', 'symbol' => 'د.ل', 'id' => 88],
            'LTC' => ['name' => 'Litecoin', 'symbol' => 'Ł', 'id' => 89],
            'LTL' => [
                'name' => 'Lithuanian Litas',
                'symbol' => 'Lt',
                'id' => 90,
            ],
            'MOP' => ['name' => 'Macanese Pataca', 'symbol' => '$', 'id' => 91],
            'MKD' => [
                'name' => 'Macedonian Denar',
                'symbol' => 'ден',
                'id' => 92,
            ],
            'MGA' => [
                'name' => 'Malagasy Ariary',
                'symbol' => 'Ar',
                'id' => 93,
            ],
            'MWK' => [
                'name' => 'Malawian Kwacha',
                'symbol' => 'MK',
                'id' => 94,
            ],
            'MYR' => [
                'name' => 'Malaysian Ringgit',
                'symbol' => 'RM',
                'id' => 95,
            ],
            'MVR' => [
                'name' => 'Maldivian Rufiyaa',
                'symbol' => 'Rf',
                'id' => 96,
            ],
            'MRO' => [
                'name' => 'Mauritanian Ouguiya',
                'symbol' => 'MRU',
                'id' => 97,
            ],
            'MUR' => ['name' => 'Mauritian Rupee', 'symbol' => '₨', 'id' => 98],
            'MXN' => ['name' => 'Mexican Peso', 'symbol' => '$', 'id' => 99],
            'MDL' => ['name' => 'Moldovan Leu', 'symbol' => 'L', 'id' => 100],
            'MNT' => [
                'name' => 'Mongolian Tugrik',
                'symbol' => '₮',
                'id' => 101,
            ],
            'MAD' => [
                'name' => 'Moroccan Dirham',
                'symbol' => 'MAD',
                'id' => 102,
            ],
            'MZM' => [
                'name' => 'Mozambican Metical',
                'symbol' => 'MT',
                'id' => 103,
            ],
            'MMK' => ['name' => 'Myanmar Kyat', 'symbol' => 'K', 'id' => 104],
            'NAD' => [
                'name' => 'Namibian Dollar',
                'symbol' => '$',
                'id' => 105,
            ],
            'NPR' => ['name' => 'Nepalese Rupee', 'symbol' => '₨', 'id' => 106],
            'ANG' => [
                'name' => 'Netherlands Antillean Guilder',
                'symbol' => 'ƒ',
                'id' => 107,
            ],
            'TWD' => [
                'name' => 'New Taiwan Dollar',
                'symbol' => '$',
                'id' => 108,
            ],
            'NZD' => [
                'name' => 'New Zealand Dollar',
                'symbol' => '$',
                'id' => 109,
            ],
            'NIO' => [
                'name' => 'Nicaraguan Córdoba',
                'symbol' => 'C$',
                'id' => 110,
            ],
            'NGN' => ['name' => 'Nigerian Naira', 'symbol' => '₦', 'id' => 111],
            'KPW' => [
                'name' => 'North Korean Won',
                'symbol' => '₩',
                'id' => 112,
            ],
            'NOK' => [
                'name' => 'Norwegian Krone',
                'symbol' => 'kr',
                'id' => 113,
            ],
            'OMR' => ['name' => 'Omani Rial', 'symbol' => '.ع.ر', 'id' => 114],
            'PKR' => [
                'name' => 'Pakistani Rupee',
                'symbol' => '₨',
                'id' => 115,
            ],
            'PAB' => [
                'name' => 'Panamanian Balboa',
                'symbol' => 'B/.',
                'id' => 116,
            ],
            'PGK' => [
                'name' => 'Papua New Guinean Kina',
                'symbol' => 'K',
                'id' => 117,
            ],
            'PYG' => [
                'name' => 'Paraguayan Guarani',
                'symbol' => '₲',
                'id' => 118,
            ],
            'PEN' => [
                'name' => 'Peruvian Nuevo Sol',
                'symbol' => 'S/.',
                'id' => 119,
            ],
            'PHP' => [
                'name' => 'Philippine Peso',
                'symbol' => '₱',
                'id' => 120,
            ],
            'PLN' => ['name' => 'Polish Zloty', 'symbol' => 'zł', 'id' => 121],
            'QAR' => ['name' => 'Qatari Rial', 'symbol' => 'ق.ر', 'id' => 122],
            'RON' => ['name' => 'Romanian Leu', 'symbol' => 'lei', 'id' => 123],
            'RUB' => ['name' => 'Russian Ruble', 'symbol' => '₽', 'id' => 124],
            'RWF' => [
                'name' => 'Rwandan Franc',
                'symbol' => 'FRw',
                'id' => 125,
            ],
            'SVC' => [
                'name' => 'Salvadoran Colón',
                'symbol' => '₡',
                'id' => 126,
            ],
            'WST' => ['name' => 'Samoan Tala', 'symbol' => 'SAT', 'id' => 127],
            'STD' => [
                'name' => 'São Tomé and Príncipe Dobra',
                'symbol' => 'Db',
                'id' => 128,
            ],
            'SAR' => ['name' => 'Saudi Riyal', 'symbol' => '﷼', 'id' => 129],
            'RSD' => [
                'name' => 'Serbian Dinar',
                'symbol' => 'din',
                'id' => 130,
            ],
            'SCR' => [
                'name' => 'Seychellois Rupee',
                'symbol' => 'SRe',
                'id' => 131,
            ],
            'SLL' => [
                'name' => 'Sierra Leonean Leone',
                'symbol' => 'Le',
                'id' => 132,
            ],
            'SGD' => [
                'name' => 'Singapore Dollar',
                'symbol' => '$',
                'id' => 133,
            ],
            'SKK' => ['name' => 'Slovak Koruna', 'symbol' => 'Sk', 'id' => 134],
            'SBD' => [
                'name' => 'Solomon Islands Dollar',
                'symbol' => 'Si$',
                'id' => 135,
            ],
            'SOS' => [
                'name' => 'Somali Shilling',
                'symbol' => 'Sh.so.',
                'id' => 136,
            ],
            'ZAR' => [
                'name' => 'South African Rand',
                'symbol' => 'R',
                'id' => 137,
            ],
            'KRW' => [
                'name' => 'South Korean Won',
                'symbol' => '₩',
                'id' => 138,
            ],
            'SSP' => [
                'name' => 'South Sudanese Pound',
                'symbol' => '£',
                'id' => 139,
            ],
            'XDR' => [
                'name' => 'Special Drawing Rights',
                'symbol' => 'SDR',
                'id' => 140,
            ],
            'LKR' => [
                'name' => 'Sri Lankan Rupee',
                'symbol' => 'Rs',
                'id' => 141,
            ],
            'SHP' => [
                'name' => 'St. Helena Pound',
                'symbol' => '£',
                'id' => 142,
            ],
            'SDG' => [
                'name' => 'Sudanese Pound',
                'symbol' => '.س.ج',
                'id' => 143,
            ],
            'SRD' => [
                'name' => 'Surinamese Dollar',
                'symbol' => '$',
                'id' => 144,
            ],
            'SZL' => [
                'name' => 'Swazi Lilangeni',
                'symbol' => 'E',
                'id' => 145,
            ],
            'SEK' => ['name' => 'Swedish Krona', 'symbol' => 'kr', 'id' => 146],
            'CHF' => ['name' => 'Swiss Franc', 'symbol' => 'CHf', 'id' => 147],
            'SYP' => ['name' => 'Syrian Pound', 'symbol' => 'LS', 'id' => 148],
            'TJS' => [
                'name' => 'Tajikistani Somoni',
                'symbol' => 'SM',
                'id' => 149,
            ],
            'TZS' => [
                'name' => 'Tanzanian Shilling',
                'symbol' => 'TSh',
                'id' => 150,
            ],
            'THB' => ['name' => 'Thai Baht', 'symbol' => '฿', 'id' => 151],
            'TOP' => ['name' => "Tongan Pa'anga", 'symbol' => '$', 'id' => 152],
            'TTD' => [
                'name' => 'Trinidad & Tobago Dollar',
                'symbol' => '$',
                'id' => 153,
            ],
            'TND' => [
                'name' => 'Tunisian Dinar',
                'symbol' => 'ت.د',
                'id' => 154,
            ],
            'TRY' => ['name' => 'Turkish Lira', 'symbol' => '₺', 'id' => 155],
            'TMT' => [
                'name' => 'Turkmenistani Manat',
                'symbol' => 'T',
                'id' => 156,
            ],
            'UGX' => [
                'name' => 'Ugandan Shilling',
                'symbol' => 'USh',
                'id' => 157,
            ],
            'UAH' => [
                'name' => 'Ukrainian Hryvnia',
                'symbol' => '₴',
                'id' => 158,
            ],
            'AED' => [
                'name' => 'United Arab Emirates Dirham',
                'symbol' => 'إ.د',
                'id' => 159,
            ],
            'UYU' => ['name' => 'Uruguayan Peso', 'symbol' => '$', 'id' => 160],
            'USD' => ['name' => 'US Dollar', 'symbol' => '$', 'id' => 161],
            'UZS' => [
                'name' => 'Uzbekistan Som',
                'symbol' => 'лв',
                'id' => 162,
            ],
            'VUV' => ['name' => 'Vanuatu Vatu', 'symbol' => 'VT', 'id' => 163],
            'VEF' => [
                'name' => 'Venezuelan BolÃvar',
                'symbol' => 'Bs',
                'id' => 164,
            ],
            'VND' => [
                'name' => 'Vietnamese Dong',
                'symbol' => '₫',
                'id' => 165,
            ],
            'YER' => ['name' => 'Yemeni Rial', 'symbol' => '﷼', 'id' => 166],
            'ZMK' => [
                'name' => 'Zambian Kwacha',
                'symbol' => 'ZK',
                'id' => 167,
            ],
            'ZWL' => [
                'name' => 'Zimbabwean dollar',
                'symbol' => '$',
                'id' => 168,
            ],
        ];
    }
}
